#!/usr/bin/env python3
"""chronicle: shared project memory stored in the repo at docs/memory/.

docs/memory/MEMORY.md is a generated index. Every other docs/memory/<slug>.md
holds one fact under a small frontmatter block (spec: references/format.md).
Git carries the store to every person, agent, machine and worktree.

Stdlib only, Python >= 3.8. Subcommands: context, index, lint, new, init,
migrate-plan, install. Each accepts --cwd DIR. Run with -h for usage.
"""

# argparse, json, shutil and subprocess are imported inside the functions that use them:
# `context` runs in every SessionStart hook and must not pay for them.
import datetime
import os
import re
import sys

SPEC_URL = "https://github.com/jnopareboateng/chronicle"
MEMORY_REL = "docs/memory"
INDEX_NAME = "MEMORY.md"
INDEX_REL = MEMORY_REL + "/" + INDEX_NAME
UNION_LINE = "docs/memory/MEMORY.md merge=union"

TYPES = ("status", "decision", "contract", "gotcha", "env", "reference")
SECTION_TITLES = {
    "status": "Status",
    "decision": "Decisions",
    "contract": "Contracts",
    "gotcha": "Gotchas",
    "env": "Environment",
    "reference": "References",
}
REQUIRED_KEYS = ("name", "description", "type", "updated")
NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]{2,63}$")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")

FILE_WARN_BYTES = 2000
FILE_ERROR_BYTES = 4000
# 100-char descriptions keep a 60-entry index near 9 KB: whole, inside the context cap.
DESCRIPTION_MAX = 100
INDEX_WARN_ENTRIES = 80
STATUS_STALE_DAYS = 21
# Claude Code shows hook stdout over 10,000 characters only as a file plus a 2,000-character
# preview, so the context must stay under that. A MEMORY.md within the cap reaches agents whole
# (context drops its header comment); past it, the tail arrives as names only.
CONTEXT_MAX_BYTES = 9000
CONTEXT_MIN_BYTES = 500
INDEX_WARN_BYTES = CONTEXT_MAX_BYTES
# context reads at most this much of MEMORY.md; past it, context says so and lint fails.
INDEX_READ_MAX = 2000000
COMPACT_HEADING = "## %s (names only; open docs/memory/<name>.md):"
COMPACT_WIDTH = 100

LEGACY_FILES = (
    "docs/memory/UPDATE_LOG.md",
    "docs/memory/PROJECT_MEMORY.md",
    "memory/UPDATE_LOG.md",
    "memory/PROJECT_MEMORY.md",
    "docs/PROJECT_MEMORY.md",
    "docs/UPDATE_LOG.md",
    "PROJECT_MEMORY.md",
    "UPDATE_LOG.md",
)
LEGACY_DIRS = ("docs/memory/updates", "memory/updates")
# Inside docs/memory these are reported as legacy, not parsed as memories.
LEGACY_STORE_NAMES = ("UPDATE_LOG.md", "PROJECT_MEMORY.md", "updates")
STATUS_SOURCES = (
    "docs/PHASE_STATUS.md",
    "docs/memory/PHASE_STATUS.md",
    "PHASE_STATUS.md",
    "docs/STATUS.md",
    "STATUS.md",
)

INDEX_HEADER = """# Project memory

<!-- Generated by chronicle from docs/memory/*.md frontmatter; edit memory files, not this list.
Memory file format (docs/memory/<slug>.md, one fact per file):
  ---
  name: <slug, same as the filename stem>
  description: <one specific line, at most 100 chars>
  type: status | decision | contract | gotcha | env | reference
  updated: YYYY-MM-DD
  ---
  <the fact first, 1-6 lines>
  **Why:** <reason, incident, or evidence>
  **How to apply:** <what to do or avoid>
To add a memory without the tool: create docs/memory/<slug>.md with the frontmatter above, then add its line below in the right section (sorted by name).
Spec: https://github.com/jnopareboateng/chronicle -->
"""

BODY_TEMPLATE = """<The fact first, 1-6 lines.>

**Why:** <reason, incident, or evidence>
**How to apply:** <what to do / avoid>
"""
TEMPLATE_PLACEHOLDERS = (
    "<The fact first",
    "<reason, incident, or evidence>",
    "<what to do / avoid>",
)

CONTEXT_HEADER = (
    "Project memory (docs/memory, shared via git; read relevant entries before work, "
    "update per the chronicle skill):"
)

SECRET_PATTERNS = (
    ("API key (sk-...)", re.compile(r"(?<![A-Za-z0-9_-])sk-[A-Za-z0-9]{20,}")),
    ("API key (sk-ant/sk-proj)", re.compile(r"\bsk-(?:ant|proj|svcacct|admin)-[A-Za-z0-9_-]{20,}")),
    ("GitHub token", re.compile(r"ghp_[A-Za-z0-9]{20,}")),
    ("GitHub token", re.compile(r"github_pat_[A-Za-z0-9_]{20,}")),
    ("AWS access key id", re.compile(r"AKIA[0-9A-Z]{16}")),
    ("Slack token", re.compile(r"\bxox[abprs]-[A-Za-z0-9-]{10,}")),
    ("private key block", re.compile(r"-----BEGIN .*PRIVATE KEY-----")),
)
# Only the <<<<<<< and >>>>>>> lines: a bare ======= is also a Markdown setext heading underline.
CONFLICT_RE = re.compile(r"^(?:<<<<<<<|>>>>>>>)(?: |$)", re.M)
LAST_UPDATED_RE = re.compile(r"^\s*[*_>#\s-]*Last Updated[*_]*\s*:", re.M | re.I)
NARRATION_RE = re.compile(r"\b(Claude|Codex|Opus|Sonnet|Haiku|GPT-\d|subagent|this session)\b")
EMAIL_RE = re.compile(r"\b([A-Za-z0-9._%+-]+)@([A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)*\.[A-Za-z]{2,})\b")
PHONE_RES = (
    re.compile(r"(?<![\w/.:+-])\+\d{1,3}[ .-]?\(?\d{1,4}\)?(?:[ .-]?\d{2,4}){2,4}(?![\w/-]|\.\w)"),
    re.compile(r"(?<![\w/.:-])\(?\d{3}\)?[ .-]\d{3}[ .-]\d{4}(?![\w/-]|\.\w)"),
)
RELATED_RE = re.compile(r"\[\[([^\]\s]+)\]\]")
ENTRY_LINE_RE = re.compile(r"^- \[[^\]]*\]\(([^)]*)\)")

# Claude Code reports forked sessions (--fork-session, /fork, /branch, backgrounded) as `fork`
# since v2.1.214 (as `resume` before). Codex documents only the four sources below.
HOOK_MATCHERS = {
    "claude": "startup|resume|clear|compact|fork",
    "codex": "startup|resume|clear|compact",
}
HOOK_TIMEOUT = 10
# Codex spills hook context over additionalContextLimit (approximate tokens, default 2500) to a
# file. 4000 covers the 9000-byte context cap even at 2.25 bytes per token.
CODEX_CONTEXT_LIMIT = 4000
# Defaults only: a reinstall keeps the values already on an existing chronicle handler.
HOOK_USER_KEYS = ("timeout", "additionalContextLimit")
HOOK_SCAN_DIRS = (".githooks", ".husky", ".claude/hooks")
HOOK_SCAN_FILES = (
    ".codex/hooks.json",
    ".codex/config.toml",
    ".pre-commit-config.yaml",
    "lefthook.yml",
    ".lefthook.yml",
)
HOOK_RE = re.compile(r"UPDATE_LOG|PROJECT_MEMORY|PHASE_STATUS|stamp|memor(?:y|ies)", re.I)
INSTRUCTION_FILES = (
    "AGENTS.md",
    "AGENTS.override.md",
    "CLAUDE.md",
    "CLAUDE.local.md",
    ".claude/CLAUDE.md",
    ".github/copilot-instructions.md",
)
INSTRUCTION_RE = re.compile(r"UPDATE_LOG|PROJECT_MEMORY")
ATTRIBUTE_FILES = (".gitattributes", "docs/.gitattributes", "docs/memory/.gitattributes", "memory/.gitattributes")
# Legacy log files and paths under a memory/ directory. PHASE_STATUS.md is not memory: it stays.
ATTRIBUTE_RE = re.compile(r"UPDATE_LOG|PROJECT_MEMORY|(?:^|/)memory/", re.I)
# Of those, only rules whose path targets a legacy file or updates/ directory count as legacy.
LEGACY_ATTRIBUTE_RE = re.compile(r"UPDATE_LOG|PROJECT_MEMORY|(?:^|/)updates(?:/|$)", re.I)


class ChronicleError(Exception):
    """A user-facing failure: printed without a traceback, exit status 2."""


class FrontmatterError(ValueError):
    pass


# --------------------------------------------------------------------------- paths


def find_root(start):
    """Walk up from start to the directory holding .git (a dir, or a file in worktrees)."""
    d = os.path.abspath(start)
    while True:
        if os.path.exists(os.path.join(d, ".git")):
            return d
        parent = os.path.dirname(d)
        if parent == d:
            return None
        d = parent


def repo_root(cwd):
    if not os.path.isdir(cwd):
        raise ChronicleError("not a directory: %s" % cwd)
    return find_root(cwd) or os.path.abspath(cwd)


def rpath(root, rel):
    return os.path.join(root, *rel.split("/"))


def display(root, path):
    try:
        rel = os.path.relpath(path, root)
    except ValueError:  # different drive on Windows
        return path
    if rel.startswith(".."):
        return path
    return rel.replace(os.sep, "/")


def read_text(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def write_text(path, text):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def human_size(n):
    return "%d B" % n if n < 1024 else "%.1f KB" % (n / 1024.0)


def today():
    return datetime.date.today()


# --------------------------------------------------------------------------- frontmatter


_KEY_LINE = re.compile(r"^([A-Za-z_][A-Za-z0-9_-]*)[ \t]*:[ \t]*(.*?)[ \t]*$")


def is_quoted(value):
    return len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'"


def unquote(value):
    v = value.strip()
    if is_quoted(v):
        inner = v[1:-1]
        if v[0] == "'":
            return inner.replace("''", "'")
        return re.sub(r'\\(["\\])', r"\1", inner)
    return v


# Lint: plain (unquoted) YAML scalars that YAML tools reject or read differently: a leading
# indicator character, `: ` (mapping), ` #` (comment) or a trailing colon.
_YAML_PLAIN_UNSAFE = re.compile(r"""^(?:[-?:](?:\s|$)|[,\[\]{}#&*!|>'"%@`])|:\s|\s#|:$""")


def yaml_scalar(value):
    """Render a one-line value that our parser and YAML parsers read back as the same string.

    Always single-quoted: a plain scalar can read as null, a boolean, a number or a date, and
    single quotes have one escape only (a doubled ').
    """
    return "'" + value.replace("'", "''") + "'"


def split_frontmatter(text):
    """Split a memory file into ([(line_no, key, raw_value)], body)."""
    if text.startswith("\ufeff"):
        text = text[1:]
    lines = text.splitlines()
    if not lines or lines[0].rstrip() != "---":
        raise FrontmatterError("missing frontmatter (first line must be ---)")
    end = None
    for i in range(1, len(lines)):
        if lines[i].rstrip() == "---":
            end = i
            break
    if end is None:
        raise FrontmatterError("frontmatter is not closed with ---")
    pairs = []
    for n in range(1, end):
        line = lines[n]
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        m = _KEY_LINE.match(line)
        if not m:
            raise FrontmatterError("line %d is not `key: value`" % (n + 1))
        pairs.append((n + 1, m.group(1), m.group(2)))
    body = "\n".join(lines[end + 1:]).strip("\n")
    return pairs, body


def parse_frontmatter(text):
    """Split a memory file into (meta, body). Flat `key: value` lines, optional quotes."""
    pairs, body = split_frontmatter(text)
    meta = {}
    for _, key, raw in pairs:
        if key in meta:
            shown = "`%s`" % key if re.fullmatch(r"[a-z_]{1,20}", key) else "(%d-char key not shown)" % len(key)
            raise FrontmatterError("duplicate key %s" % shown)
        meta[key] = unquote(raw)
    return meta, body


# --------------------------------------------------------------------------- store


class Memory(object):
    __slots__ = ("path", "rel", "stem", "size", "text", "meta", "body", "error")

    def __init__(self, path, rel):
        self.path, self.rel = path, rel
        self.stem = os.path.basename(path)[:-3]
        self.size = 0
        self.text = None
        self.meta = {}
        self.body = ""
        self.error = None

    @property
    def indexable(self):
        return self.error is None and self.meta.get("type") in TYPES


def read_memory(path, rel):
    m = Memory(path, rel)
    try:
        with open(path, "rb") as f:
            raw = f.read()
    except OSError as e:
        m.error = "unreadable (%s)" % (e.strerror or e)
        return m
    m.size = len(raw)
    try:
        m.text = raw.decode("utf-8")
    except UnicodeDecodeError:
        m.error = "not valid UTF-8"
        return m
    try:
        m.meta, m.body = parse_frontmatter(m.text)
    except FrontmatterError as e:
        m.error = "bad frontmatter: %s" % e
    return m


def scan_store(root):
    """Return (memories, other_paths) for docs/memory; legacy files are skipped.

    A missing store is empty. A store that exists but cannot be listed is an error: treating it
    as empty would let `index` write an index without any entry.
    """
    memdir = rpath(root, MEMORY_REL)
    memories, others = [], []
    try:
        names = sorted(os.listdir(memdir))
    except (FileNotFoundError, NotADirectoryError):
        return memories, others
    except OSError as e:
        raise ChronicleError("cannot list %s (%s); nothing written" % (MEMORY_REL, e.strerror or e))
    for name in names:
        full = os.path.join(memdir, name)
        rel = MEMORY_REL + "/" + name
        if name == INDEX_NAME or name in LEGACY_STORE_NAMES or name.startswith("."):
            continue  # dotfiles: .gitkeep, .gitattributes, editor files
        if os.path.isdir(full):
            others.append(rel + "/")
        elif not name.endswith(".md") or not os.path.isfile(full):
            others.append(rel)  # isfile: never open a FIFO or device (it would block)
        else:
            memories.append(read_memory(full, rel))
    return memories, others


def render_index(memories):
    groups = dict((t, []) for t in TYPES)
    for m in memories:
        if m.indexable:
            groups[m.meta["type"]].append(m)
    out = [INDEX_HEADER]
    for t in TYPES:
        if not groups[t]:
            continue
        out.append("\n## %s\n" % SECTION_TITLES[t])
        for m in sorted(groups[t], key=lambda x: x.stem):
            desc = " ".join(m.meta.get("description", "").split())
            out.append("- [%s](%s.md) \u2014 %s\n" % (m.stem, m.stem, desc))
    return "".join(out)


def count_entries(text):
    return sum(1 for line in text.splitlines() if ENTRY_LINE_RE.match(line))


def read_index(root):
    path = rpath(root, INDEX_REL)
    if not os.path.isfile(path):
        return None
    try:
        return read_text(path)
    except (OSError, UnicodeDecodeError):
        return None


def write_index(root, memories=None):
    """Regenerate MEMORY.md; return True when the file changed."""
    if memories is None:
        memories, _ = scan_store(root)
    text = render_index(memories)
    if read_index(root) == text:
        return False
    write_text(rpath(root, INDEX_REL), text)
    return True


def is_union_line(line):
    """True for the chronicle union line, also written root-anchored (`/docs/memory/...`)."""
    return " ".join(line.split()).lstrip("/") == UNION_LINE


def ensure_union_line(root):
    path = rpath(root, ".gitattributes")
    text = ""
    if os.path.lexists(path):
        if not os.path.isfile(path):
            raise ChronicleError("%s is not a regular file: add `%s` to it by hand" % (path, UNION_LINE))
        try:
            with open(path, encoding="utf-8", newline="") as f:
                text = f.read()
        except UnicodeDecodeError:
            raise ChronicleError("%s is not UTF-8 (git reads it as UTF-8; PowerShell 5.1 `>` writes UTF-16): "
                                 "re-save it as UTF-8; left unchanged" % path)
        except OSError as e:
            raise ChronicleError("cannot read %s (%s)" % (path, e.strerror or e))
    eol = "\r\n" if "\r\n" in text else "\n"
    out, seen, dropped = [], False, 0
    for line in text.splitlines(True):
        if is_union_line(line):
            if seen:
                dropped += 1
                continue
            seen = True
        out.append(line)
    if not seen:
        if out and not out[-1].endswith(("\n", "\r")):
            out[-1] += eol
        out.append(UNION_LINE + eol)
    new = "".join(out)
    if new == text:
        return None
    try:
        with open(path, "w", encoding="utf-8", newline="") as f:
            f.write(new)
    except OSError as e:
        raise ChronicleError("cannot write %s (%s)" % (path, e.strerror or e))
    if dropped:
        return "removed %d duplicate `%s` line(s) from .gitattributes" % (dropped, UNION_LINE)
    return "added `%s` to .gitattributes" % UNION_LINE


def ensure_store(root):
    actions = []
    memdir = rpath(root, MEMORY_REL)
    if not os.path.isdir(memdir):
        os.makedirs(memdir)
        actions.append("created %s/" % MEMORY_REL)
    if write_index(root):
        actions.append("wrote %s" % INDEX_REL)
    changed = ensure_union_line(root)
    if changed:
        actions.append(changed)
    return actions


def legacy_present(root):
    found = []
    for rel in LEGACY_FILES:
        full = rpath(root, rel)
        if os.path.isfile(full):
            try:
                size = human_size(os.path.getsize(full))
            except OSError:
                size = "?"
            found.append((rel, size))
    for rel in LEGACY_DIRS:
        full = rpath(root, rel)
        if os.path.isdir(full):
            try:
                n = len(os.listdir(full))
            except OSError:
                n = 0
            found.append((rel + "/", "%d files" % n))
    return found


# --------------------------------------------------------------------------- context


def _nbytes(line):
    """Output size of one line: UTF-8 plus its LF (stdout is reconfigured to LF everywhere)."""
    return len(line.encode("utf-8")) + 1


def _compact(groups):
    """Names-only lines for [(section, [names])]: one heading per section, then the names
    comma-separated and wrapped. A wrap turns ", " into ",\\n", so wrapping never changes the
    byte count _fit plans with: heading line + names + 2 bytes per name after the first + LF."""
    out = []
    for section, names in groups:
        out.append(COMPACT_HEADING % section)
        line = ""
        for i, name in enumerate(names):
            piece = name + ("," if i + 1 < len(names) else "")
            if line and len(line) + 1 + len(piece) > COMPACT_WIDTH:
                out.append(line)
                line = piece
            else:
                line = line + " " + piece if line else piece
        out.append(line)
    return out


def _group(rows):
    """[(section, [names])] for the entry rows, one group per heading run."""
    groups = []
    for gid, title, name in rows:
        if name is None:
            continue
        if not groups or groups[-1][0] != gid:
            groups.append((gid, title, []))
        groups[-1][2].append(name)
    return [(title, names) for _, title, names in groups]


def _fit(head, body, max_bytes):
    """head + body within max_bytes, never dropping an entry without its name.

    Full lines go first, in index order, while the names of everything after them still fit.
    From the first line that would break that, the rest is names only, per section. Only when
    even the names overflow does the output end with a count of the entries left out.
    """
    used = sum(_nbytes(line) for line in head)
    if used + sum(_nbytes(line) for line in body) <= max_bytes:
        return head + body
    rows, gid, title = [], 0, "Other"  # per line: (heading run, section title, entry name or None)
    for line in body:
        name = None
        if line.startswith("## "):
            gid, title = gid + 1, line[3:].strip() or "Other"
        else:
            m = ENTRY_LINE_RE.match(line)
            if m and m.group(1):
                name = m.group(1)[:-3] if m.group(1).endswith(".md") else m.group(1)
        rows.append((gid, title, name))
    note = "... (more lines in %s)" % INDEX_REL
    n = len(body)
    # tail[i]: bytes of body[i:] in compact form; other[i]: body[i:] holds a line that is neither
    # heading nor entry (compact form drops it, so the note is added).
    tail, other = [0] * (n + 1), [False] * (n + 1)
    later, cur, cur_bytes = 0, None, 0
    for i in range(n - 1, -1, -1):
        g, t, name = rows[i]
        if name is not None:
            if g != cur:
                later, cur, cur_bytes = later + cur_bytes, g, _nbytes(COMPACT_HEADING % t) - 1
            cur_bytes += len(name.encode("utf-8")) + 2
        other[i] = other[i + 1] or (name is None and not body[i].startswith("## "))
        tail[i] = later + cur_bytes + (_nbytes(note) if other[i] else 0)
    if used + tail[0] <= max_bytes:
        taken = 0
        while taken < n and used + _nbytes(body[taken]) + tail[taken + 1] <= max_bytes:
            used += _nbytes(body[taken])
            taken += 1
        full = body[:taken]
        while full and full[-1].startswith("## "):  # a heading whose entries all went compact
            full.pop()
        return head + full + _compact(_group(rows[taken:])) + ([note] if other[taken] else [])
    total = sum(1 for row in rows if row[2] is not None)
    budget = max_bytes - used - _nbytes("... %d more in %s" % (total, INDEX_REL))
    shown, spent, last = [], 0, None
    for row in rows:
        if row[2] is None:
            continue
        cost = len(row[2].encode("utf-8")) + (2 if row[0] == last else _nbytes(COMPACT_HEADING % row[1]) + 1)
        if spent + cost > budget:
            break
        shown.append(row)
        spent, last = spent + cost, row[0]
    return head + _compact(_group(shown)) + ["... %d more in %s" % (total - len(shown), INDEX_REL)]


# The generated header comment: after only the `# ` title and blank lines, it starts with the
# generated marker and closes before any entry line or section heading.
_HEADER_COMMENT_RE = re.compile(
    r"\A(﻿?(?:[ \t]*(?:#[ \t][^\n]*)?\n)*)[ \t]*<!-- Generated by chronicle(?:(?!\n- \[|\n## ).)*?-->", re.S)


def strip_header_comment(text):
    """Remove the generated header comment only; any other comment, and every entry, is kept.

    Entry descriptions may themselves contain `<!--` or `-->`; they are never touched.
    """
    return _HEADER_COMMENT_RE.sub(r"\1", text, count=1)


def context_text(root, max_bytes=CONTEXT_MAX_BYTES):
    max_bytes = max(max_bytes, CONTEXT_MIN_BYTES)
    legacy = legacy_present(root)
    index_path = rpath(root, INDEX_REL)
    if os.path.isfile(index_path):
        with open(index_path, "rb") as f:
            raw = f.read(INDEX_READ_MAX + 1)
        head = [CONTEXT_HEADER]
        if legacy:
            head.append(
                "Legacy memory files still present (%s): do not bulk-read them; finish the "
                "migration per the chronicle skill." % ", ".join(rel for rel, _ in legacy)
            )
        if len(raw) > INDEX_READ_MAX:
            raw = raw[:INDEX_READ_MAX]
            head.append("(%s is over %d bytes: entries past that point are not shown; run chronicle lint)"
                        % (INDEX_REL, INDEX_READ_MAX))
        if b"\x00" in raw:
            return "\n".join(head + ["(%s is unreadable; run chronicle lint)" % INDEX_REL]) + "\n"
        text = strip_header_comment(raw.decode("utf-8", "replace").replace("\r\n", "\n"))
        body = [
            line.rstrip()
            for line in text.split("\n")
            if line.strip() and not re.match(r"^#\s+Project memory\s*$", line)
        ]
        if not body:
            body = ["(no entries yet)"]
        return "\n".join(_fit(head, body, max_bytes)) + "\n"
    if legacy:
        listing = ", ".join("%s (%s)" % item for item in legacy)
        return (
            "Legacy project memory (not yet migrated to chronicle docs/memory entries): %s.\n"
            "Do NOT bulk-read UPDATE_LOG.md or updates/. When relevant, read only the section "
            "headings of PROJECT_MEMORY.md (e.g. rg -n '^#' <file>) and open matching sections; "
            "migration is described in the chronicle skill (migrate).\n" % listing
        )
    return ""


def _context_args(argv):
    cwd, max_bytes = ".", CONTEXT_MAX_BYTES
    i = 0
    while i < len(argv):
        a = argv[i]
        if a.startswith("--cwd="):
            cwd = a.split("=", 1)[1]
        elif a == "--cwd" and i + 1 < len(argv):
            i += 1
            cwd = argv[i]
        elif a.startswith("--max-bytes="):
            max_bytes = int(a.split("=", 1)[1])
        elif a == "--max-bytes" and i + 1 < len(argv):
            i += 1
            max_bytes = int(argv[i])
        i += 1
    return cwd, max_bytes


def run_context_hook(argv):
    """SessionStart entry point: print the index, or nothing. Never fails, always exit 0."""
    try:
        _utf8_stdio()
        cwd, max_bytes = _context_args(argv)
        root = find_root(cwd) or os.path.abspath(cwd)
        text = context_text(root, max_bytes)
        if text:
            sys.stdout.write(text)
            sys.stdout.flush()
    except BaseException:
        pass
    os._exit(0)


# --------------------------------------------------------------------------- lint


def _line_of(text, pos):
    return text.count("\n", 0, pos) + 1


def _find_email(text):
    for m in EMAIL_RE.finditer(text):
        local, domain = m.group(1).lower(), m.group(2).lower()
        if local in ("git", "noreply", "no-reply") or domain.split(".")[0] in ("example", "users"):
            continue
        return m.start()
    return None


def _find_phone(text):
    for rx in PHONE_RES:
        for m in rx.finditer(text):
            digits = sum(c.isdigit() for c in m.group(0))
            if 9 <= digits <= 15:
                return m.start()
    return None


def lint_memory(m, names, today_date):
    """Findings for one memory file: list of (level, message)."""
    out = []
    err = lambda msg: out.append(("ERROR", msg))  # noqa: E731
    warn = lambda msg: out.append(("WARN", msg))  # noqa: E731
    if m.text is None:
        err(m.error)
        return out
    text = m.text
    for label, rx in SECRET_PATTERNS:
        hit = rx.search(text)
        if hit:
            err("possible secret (%s) at line %d: remove it and rotate the credential" % (label, _line_of(text, hit.start())))
    hit = CONFLICT_RE.search(text)
    if hit:
        err("git conflict marker at line %d" % _line_of(text, hit.start()))
    if not text.lstrip("\ufeff").startswith("---"):
        # A plain document, not a memory: one finding, not a pile of format noise.
        err("missing frontmatter: not a memory file; move it out of docs/memory or rewrite it as entries")
        return out
    if m.size > FILE_ERROR_BYTES:
        err("%d bytes exceeds the %d byte limit: split it into one fact per file" % (m.size, FILE_ERROR_BYTES))
    elif m.size > FILE_WARN_BYTES:
        warn("%d bytes exceeds the %d byte budget: tighten it" % (m.size, FILE_WARN_BYTES))
    hit = LAST_UPDATED_RE.search(text)
    if hit:
        err("`Last Updated:` line at line %d: use the `updated:` field" % _line_of(text, hit.start()))
    for placeholder in TEMPLATE_PLACEHOLDERS:
        if placeholder in text:
            err("unfilled template placeholder `%s`" % placeholder)
            break
    if m.error:
        err(m.error)
    else:
        # Messages name the field and the value's length, never the value: a credential pasted
        # into a field must not be copied into terminal output, agent context or logs.
        meta = m.meta
        missing = [k for k in REQUIRED_KEYS if not meta.get(k)]
        if missing:
            err("missing frontmatter field(s): %s" % ", ".join(missing))
        name = meta.get("name", "")
        if name and not NAME_RE.match(name):
            err("invalid name (%d-char value not shown): use 3-64 chars of a-z, 0-9 and -" % len(name))
        if name and name != m.stem:
            err("name does not match filename: name must equal the filename stem")
        if not NAME_RE.match(m.stem):
            err("invalid filename: use 3-64 chars of a-z, 0-9 and - before .md")
        mtype = meta.get("type", "")
        if mtype and mtype not in TYPES:
            err("invalid type (%d-char value not shown): use one of %s" % (len(mtype), ", ".join(TYPES)))
        if mtype == "status" and not m.stem.startswith("status-"):
            err("status entries must be named status-<branch or topic>")
        updated = meta.get("updated", "")
        updated_date = None
        if updated:
            try:
                if not DATE_RE.match(updated):
                    raise ValueError
                updated_date = datetime.datetime.strptime(updated, "%Y-%m-%d").date()
            except ValueError:
                err("invalid updated date (%d-char value not shown): use YYYY-MM-DD" % len(updated))
        desc = meta.get("description", "")
        if len(desc) > DESCRIPTION_MAX:
            warn("description is %d chars (budget %d)" % (len(desc), DESCRIPTION_MAX))
        if "<!--" in desc or "-->" in desc:
            warn("description contains `<!--` or `-->`: rendered MEMORY.md would hide index lines; reword it")
        for n, key, raw in split_frontmatter(text)[0]:
            if raw and not is_quoted(raw) and _YAML_PLAIN_UNSAFE.search(raw):
                warn("unquoted `%s` at line %d is invalid or truncated YAML (`: `, ` #`, a leading symbol "
                     "or a trailing colon): wrap the value in double quotes" % (key, n))
        if not m.body.strip():
            warn("empty body: state the fact, then **Why:** and **How to apply:**")
        if mtype == "status" and updated_date is not None:
            age = (today_date - updated_date).days
            if age > STATUS_STALE_DAYS:
                warn("status entry not updated for %d days: refresh it, or delete it if the work merged" % age)
        for link in RELATED_RE.findall(m.body):
            if link not in names:
                shown = "[[%s]]" % link if NAME_RE.fullmatch(link) else "(%d-char link not shown)" % len(link)
                warn("related link %s has no matching memory file" % shown)
    pos = _find_email(text)
    if pos is not None:
        warn("email-like string at line %d: no personal data in memory" % _line_of(text, pos))
    pos = _find_phone(text)
    if pos is not None:
        warn("phone-number-like string at line %d: no personal data in memory" % _line_of(text, pos))
    hit = NARRATION_RE.search(text)
    if hit:
        warn("process narration term `%s` at line %d: record the fact, not who or what produced it"
             % (hit.group(1), _line_of(text, hit.start())))
    return out


def lint_store(root):
    """Return (findings, memory_count); findings are (level, path, message)."""
    findings = []
    add = lambda level, path, msg: findings.append((level, path, msg))  # noqa: E731
    memories, others = scan_store(root)
    if not os.path.isdir(rpath(root, MEMORY_REL)):
        add("ERROR", MEMORY_REL, "missing (run chronicle init)")
    else:
        names = set(m.stem for m in memories)
        today_date = today()
        descriptions = {}
        for m in memories:
            for level, msg in lint_memory(m, names, today_date):
                add(level, m.rel, msg)
            desc = " ".join(m.meta.get("description", "").split()).lower()
            if desc:
                if desc in descriptions:
                    add("WARN", m.rel, "same description as %s: merge duplicates" % descriptions[desc])
                else:
                    descriptions[desc] = m.rel
        for rel in others:
            add("WARN", rel, "not a memory file: docs/memory holds only MEMORY.md and <slug>.md memories")
        expected = render_index(memories)
        actual = read_index(root)
        if actual is None:
            add("ERROR", INDEX_REL, "missing or unreadable (run chronicle index)")
        else:
            try:
                size = os.path.getsize(rpath(root, INDEX_REL))
            except OSError:
                size = 0
            if size > INDEX_READ_MAX:
                add("ERROR", INDEX_REL, "%d bytes exceeds the %d byte read limit: session-start context omits "
                    "the entries past it; curate, then run chronicle index" % (size, INDEX_READ_MAX))
            hit = CONFLICT_RE.search(actual)
            if hit:
                add("ERROR", INDEX_REL, "git conflict marker at line %d" % _line_of(actual, hit.start()))
            targets = {}
            for line in actual.splitlines():
                em = ENTRY_LINE_RE.match(line)
                if em:
                    targets[em.group(1)] = targets.get(em.group(1), 0) + 1
            for target in sorted(t for t, n in targets.items() if n > 1):
                add("ERROR", INDEX_REL, "duplicate index lines for %s (%d lines): run chronicle index"
                    % (target, targets[target]))
            if actual != expected:
                exp_lines, act_lines = set(expected.splitlines()), set(actual.splitlines())
                detail = ["%d %s lines" % (n, kind) for n, kind in (
                    (len(exp_lines - act_lines), "missing"), (len(act_lines - exp_lines), "stale")) if n]
                add("ERROR", INDEX_REL, "out of date with the memory files%s: run chronicle index"
                    % (" (%s)" % ", ".join(detail) if detail else ""))
        n_entries = count_entries(expected)
        if n_entries > INDEX_WARN_ENTRIES:
            add("WARN", INDEX_REL, "%d entries (budget %d): curate, merge or delete" % (n_entries, INDEX_WARN_ENTRIES))
        n_bytes = len(expected.encode("utf-8"))
        if n_bytes > INDEX_WARN_BYTES:
            add("WARN", INDEX_REL, "%d bytes (budget %d): session-start context lists the tail by name only; "
                "curate or shorten descriptions" % (n_bytes, INDEX_WARN_BYTES))
    for rel, size in legacy_present(root):
        add("WARN", rel, "legacy memory (%s): migrate per the chronicle skill (references/migrate.md)" % size)
    return findings, sum(1 for m in memories if m.indexable)


# --------------------------------------------------------------------------- migrate-plan


def _git(root, *args):
    """Run git in root; return (returncode, stdout) or (None, '') when git is unusable."""
    import subprocess

    try:
        r = subprocess.run(
            ["git", "-C", root] + list(args),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            universal_newlines=True,
            timeout=15,
        )
        return r.returncode, r.stdout
    except (OSError, subprocess.SubprocessError):
        return None, ""


def _git_usable(root):
    rc, out = _git(root, "rev-parse", "--show-toplevel")
    if rc != 0 or not out.strip():
        return False
    try:
        return os.path.samefile(out.strip(), root)
    except OSError:
        return os.path.normcase(os.path.realpath(out.strip())) == os.path.normcase(os.path.realpath(root))


def _git_dirs_by_hand(root):
    """(gitdir, commondir) without running git."""
    dotgit = os.path.join(root, ".git")
    if os.path.isdir(dotgit):
        return dotgit, dotgit
    try:
        with open(dotgit, encoding="utf-8") as f:
            line = f.readline().strip()
    except OSError:
        return None, None
    if not line.startswith("gitdir:"):
        return None, None
    gitdir = line.split(":", 1)[1].strip()
    if not os.path.isabs(gitdir):
        gitdir = os.path.normpath(os.path.join(root, gitdir))
    common = gitdir
    try:
        with open(os.path.join(gitdir, "commondir"), encoding="utf-8") as f:
            c = f.read().strip()
        common = c if os.path.isabs(c) else os.path.normpath(os.path.join(gitdir, c))
    except OSError:
        pass
    return gitdir, common


def _git_layout(root, use_git):
    """(common_dir, hooks_dir, main_checkout).

    common_dir is the git dir all worktrees share; hooks_dir is the one git runs (it follows
    core.hooksPath); main_checkout is the main worktree, which Claude Code keys auto memory by.
    """
    common = hooks = None
    if use_git:
        found = []
        for args in (("rev-parse", "--git-common-dir"), ("rev-parse", "--git-path", "hooks")):
            rc, out = _git(root, *args)
            d = out.strip() if rc == 0 else ""
            found.append(os.path.normpath(os.path.join(root, d)) if d else None)  # join keeps absolute d
        common, hooks = found
    if not common:
        _, common = _git_dirs_by_hand(root)
        common = common and os.path.normpath(common)
    if common and not hooks:
        hooks = os.path.join(common, "hooks")
    main = os.path.dirname(common) if common and os.path.basename(common) == ".git" else root
    return common, hooks, main


def _inside(path, top):
    """path relative to top when path lies inside top (real paths compared), else None."""
    try:
        rel = os.path.relpath(os.path.realpath(path), os.path.realpath(top))
    except ValueError:  # another drive on Windows
        return None
    if rel == os.curdir or rel == os.pardir or rel.startswith(os.pardir + os.sep):
        return None
    return rel


def _hook_dirs(root, layout):
    """Hook directories to scan. A hooks dir inside the main checkout (an absolute core.hooksPath,
    shared by every worktree) is read from this worktree's copy when it has one: that copy is
    the one this branch edits, and scanning both would list the same hooks twice."""
    common, hooks, main = layout
    dirs = [rpath(root, d) for d in HOOK_SCAN_DIRS]
    for d in (hooks, common and os.path.join(common, "hooks")):
        rel = d and _inside(d, main)
        local = rel and os.path.join(root, rel)
        dirs.append(local if local and os.path.isdir(local) else d)
    return [d for d in dirs if d]


def _hooks_path_note(root, use_git, main):
    if not use_git:
        return None
    rc, out = _git(root, "config", "--path", "--get", "core.hooksPath")
    value = out.strip()
    if rc != 0 or not value or not os.path.isabs(value):
        return None
    where = "worktrees run the main checkout's hooks" if _inside(value, main) else "every worktree runs these hooks"
    return "core.hooksPath is absolute (%s): %s" % (value, where)


def claude_project_slug(path):
    """Claude Code's ~/.claude/projects/<slug> name for a path: each non-alphanumeric becomes '-'."""
    return re.sub(r"[^A-Za-z0-9]", "-", path)


def _claude_auto_memory(main):
    """(auto memory dir for the main checkout on this machine, file count or None if absent)."""
    base = os.path.expanduser(os.environ.get("CLAUDE_CONFIG_DIR") or os.path.join("~", ".claude"))
    path = os.path.join(base, "projects", claude_project_slug(main), "memory")
    try:
        return path, sum(1 for f in os.listdir(path) if not f.startswith("."))
    except OSError:
        return path, None


def _grep_file(path, rx, limit=1000000):
    """Yield (lineno, line) for lines of a text file matching rx."""
    if not os.path.isfile(path):  # also skips FIFOs and devices, which would block
        return
    try:
        if os.path.getsize(path) > limit:
            return
        with open(path, "rb") as f:
            raw = f.read()
    except OSError:
        return
    if b"\x00" in raw[:4096]:
        return
    for n, line in enumerate(raw.decode("utf-8", "replace").splitlines(), 1):
        if rx.search(line):
            yield n, line.strip()


def _clip(s, n=160):
    return s if len(s) <= n else s[: n - 3] + "..."


def _walk_files(top, max_depth=2):
    if not os.path.isdir(top):
        return
    base = top.rstrip(os.sep).count(os.sep)
    for dirpath, dirnames, filenames in os.walk(top):
        if dirpath.count(os.sep) - base >= max_depth:
            dirnames[:] = []
        dirnames.sort()
        for name in sorted(filenames):
            if not name.endswith(".sample"):
                yield os.path.join(dirpath, name)


def _legacy_inventory(root):
    """Return (files, dirs): [(rel, detail)] for legacy memory present in root."""
    files, dirs = [], []
    for rel in LEGACY_FILES:
        full = rpath(root, rel)
        if not os.path.isfile(full):
            continue
        try:
            with open(full, "rb") as f:
                text = f.read().decode("utf-8", "replace")
        except OSError:
            continue
        headings = len(re.findall(r"^## ", text, re.M))
        stamps = len(LAST_UPDATED_RE.findall(text))
        files.append((rel, "%s, %d lines, %d `## ` headings, %d `Last Updated:` lines"
                      % (human_size(len(text.encode("utf-8"))), text.count("\n"), headings, stamps)))
    for rel in LEGACY_DIRS:
        full = rpath(root, rel)
        if not os.path.isdir(full):
            continue
        count = total = 0
        for dirpath, _, filenames in os.walk(full):
            for name in filenames:
                count += 1
                try:
                    total += os.path.getsize(os.path.join(dirpath, name))
                except OSError:
                    pass
        dirs.append((rel + "/", "%d files, %s" % (count, human_size(total))))
    return files, dirs


def _non_memory_docs(root, skip):
    """Files in docs/memory and memory/ that are neither legacy, the index, nor parseable memories."""
    good = set(m.rel for m in scan_store(root)[0] if m.error is None)
    out = []
    for rel_dir in (MEMORY_REL, "memory"):
        full = rpath(root, rel_dir)
        if not os.path.isdir(full):
            continue
        for name in sorted(os.listdir(full)):
            rel = rel_dir + "/" + name
            is_dir = os.path.isdir(os.path.join(full, name))
            if name.startswith(".") or rel == INDEX_REL or rel in good or (rel + "/" if is_dir else rel) in skip:
                continue
            out.append(rel + ("/" if is_dir else ""))
    return out


def _hook_references(root, layout, per_file=5):
    """Return (report lines, files with hits) for hooks and tooling that mention memory."""
    paths, scanned = [], set()
    for top in _hook_dirs(root, layout):
        paths.extend(_walk_files(top))
    claude_dir = rpath(root, ".claude")
    if os.path.isdir(claude_dir):
        paths.extend(os.path.join(claude_dir, f) for f in sorted(os.listdir(claude_dir))
                     if f.startswith("settings") and f.endswith(".json"))
    paths.extend(rpath(root, rel) for rel in HOOK_SCAN_FILES)
    lines, files = [], []
    for path in paths:
        key = os.path.normcase(os.path.realpath(path))
        if key in scanned:
            continue
        scanned.add(key)
        hits = list(_grep_file(path, HOOK_RE))
        if not hits:
            continue
        name = display(root, path)
        files.append(name)
        lines.extend("%s:%d: %s" % (name, n, _clip(t)) for n, t in hits[:per_file])
        if len(hits) > per_file:
            lines.append("%s: ... %d more matching lines" % (name, len(hits) - per_file))
    return lines, files


_CHECK_IGNORE_RE = re.compile(r"^(.*):(\d+):(.*)$")


def _ignore_rules(root, use_git):
    hits = set()
    if use_git:
        _, out = _git(root, "check-ignore", "-v", "--no-index", INDEX_REL, MEMORY_REL + "/chronicle-probe.md")
        for line in out.splitlines():
            m = _CHECK_IGNORE_RE.match(line.partition("\t")[0])
            if m and not m.group(3).startswith("!"):
                hits.add("%s:%s: %s" % (display(root, m.group(1)), m.group(2), m.group(3)))
        return sorted(hits)
    common = _git_layout(root, False)[0]
    exclude = common and os.path.join(common, "info", "exclude")
    rx = re.compile(r"docs/memory|^/?memory/?\*?$|UPDATE_LOG|PROJECT_MEMORY")
    for path in (rpath(root, ".gitignore"), rpath(root, "docs/.gitignore"), exclude):
        if path:
            hits.update("%s:%d: %s" % (display(root, path), n, t)
                        for n, t in _grep_file(path, rx) if not t.startswith("#"))
    return sorted(hits)


def migrate_plan(root):
    """Read-only inventory of legacy memory machinery plus a checklist; returns report lines."""
    use_git = _git_usable(root)
    layout = _git_layout(root, use_git)
    auto_dir, auto_files = _claude_auto_memory(layout[2])
    auto = "%s: %s" % (auto_dir, "absent" if auto_files is None else "%d files" % auto_files)
    legacy_files, legacy_dirs = _legacy_inventory(root)
    legacy = [rel for rel, _ in legacy_files + legacy_dirs]
    index = read_index(root)
    extra_docs = _non_memory_docs(root, set(legacy))
    status_sources = [rel for rel in STATUS_SOURCES if os.path.isfile(rpath(root, rel))]
    attr_hits, attr_legacy = [], 0
    for rel in ATTRIBUTE_FILES:
        for n, text in _grep_file(rpath(root, rel), ATTRIBUTE_RE):
            if text.startswith("#"):
                continue
            pattern, attrs = text.split()[0], text.split()[1:]
            if pattern.lstrip("/") == INDEX_REL and "merge=union" in attrs:
                mark = "  (keep: chronicle)"
            elif LEGACY_ATTRIBUTE_RE.search(pattern):
                mark = "  (legacy)"
                attr_legacy += 1
            else:
                mark = ""  # another rule on a memory path (e.g. docs/memory/*.md text eol=lf): not legacy
            attr_hits.append("%s:%d: %s%s" % (rel, n, _clip(text), mark))
    hook_hits, hook_files = _hook_references(root, layout)
    ignore_hits = _ignore_rules(root, use_git)
    instr_hits = ["%s:%d: %s" % (rel, n, _clip(t))
                  for rel in INSTRUCTION_FILES for n, t in _grep_file(rpath(root, rel), INSTRUCTION_RE)]
    store = "%s: %s" % (INDEX_REL, "absent" if index is None else "%d entries" % count_entries(index))

    sections = [
        ("Legacy memory", ["%s: %s" % item for item in legacy_files + legacy_dirs]),
        ("Chronicle store", [store]),
        ("Claude auto memory on this machine (shared by all worktrees of the repo)", [auto]),
        ("Non-memory files in memory dirs (move out of docs/memory, or fold facts into entries)", extra_docs),
        ("Status sources (seed status-<branch> entries only for in-flight work)", status_sources),
        (".gitattributes lines for memory files", attr_hits),
        ("Hooks and tooling mentioning memory (review; remove only memory gates, stampers, auto-commits)",
         hook_hits),
        ("Ignore rules hiding docs/memory (change only with the repo owner's agreement)", ignore_hits),
        ("Agent instructions mentioning legacy memory (replace with references/agents-snippet.md)", instr_hits),
    ]
    sources = ["read %s fully (page through it)" % rel if rel.endswith("PROJECT_MEMORY.md")
               else "scan the headings (or entry first lines) of %s" % rel for rel, _ in legacy_files]
    sources += ["scan file names and headings in %s" % rel for rel, _ in legacy_dirs]
    instr_files = sorted(set(h.split(":", 1)[0] for h in instr_hits))
    steps = [
        "Work in a sibling worktree on branch chore/memory-v2 "
        "(git worktree add ../<repo>-memory-v2 -b chore/memory-v2); leave changes uncommitted unless asked.",
        "Rebase onto the latest remote integration branch before migrating (git fetch && git rebase "
        "origin/<branch>): a stale base misses entries and conflicts on AGENTS.md.",
        "chronicle init" + ("  (store already present)" if index is not None else ""),
        "Extract durable facts: %s. Open only entries that look like decisions, incidents, contracts or env "
        "quirks; skip diaries, progress notes, test counts, narration; verify each against current code (rg) "
        "and drop facts about removed components; merge duplicates; settle contradictions with code evidence."
        % ("; ".join(sources) or "no legacy sources found"),
        "Promote project facts from Claude auto memory (%s; also other machines and OSes where Claude Code "
        "ran) into docs/memory; report the promoted files for removal there; do not delete them." % auto,
        "Write one fact per file (typically 20-60 entries); seed status-<branch> entries only for genuinely "
        "in-flight work%s." % (" (from %s)" % ", ".join(status_sources) if status_sources else ""),
        "git rm the legacy files (%s)%s." % (", ".join(legacy) or "none",
                                            "; move out non-memory docs (%s)" % ", ".join(extra_docs) if extra_docs else ""),
        "Remove legacy machinery: %d legacy .gitattributes line(s); %s."
        % (attr_legacy, "review and remove memory gates/stampers in %s (leave unrelated settings alone)"
           % ", ".join(hook_files) if hook_files else "no hook or tooling files mention memory"),
        "Ignore rules hide docs/memory: ask the repo owner before changing them." if ignore_hits
        else "No ignore rules hide docs/memory.",
        "Replace the memory rules in %s with references/agents-snippet.md." % (", ".join(instr_files) or "AGENTS.md / CLAUDE.md"),
        "Verify: chronicle lint && chronicle index --check",
    ]
    lines = ["chronicle migrate-plan: %s (read-only)" % root]
    for title, items in sections:
        lines += ["", title] + ["  " + item for item in (items or ["none"])]
    lines += ["", "Checklist (procedure: references/migrate.md in the chronicle skill)"]
    lines += ["  [ ] %d. %s" % (i, step) for i, step in enumerate(steps, 1)]
    note = _hooks_path_note(root, use_git, layout[2])
    if note:
        lines.append("  note: " + note)
    return lines


# --------------------------------------------------------------------------- install


def skill_source_dir():
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# A home under a WSL drive mount (/mnt/c/Users/...) belongs to Windows.
WSL_DRIVE_RE = re.compile(r"/mnt/[A-Za-z](?:/|$)")


def default_python():
    return "py -3" if os.name == "nt" else "python3"


def hook_command(python, script, windows=None):
    """Hook command line. Forward slashes and double quotes work in bash, PowerShell and cmd alike."""
    if os.name == "nt" if windows is None else windows:
        script = script.replace("\\", "/")
    if " " in python and not python.startswith('"') and os.path.isfile(python):
        python = '"%s"' % python  # an interpreter path with spaces, not "py -3"
    return '%s "%s" context' % (python, script)


# A chronicle handler is a whole command of the shape hook_command writes: a Python interpreter
# (py, python, python3, python3.10, optionally a path, optionally .exe, optionally double-quoted)
# with optional dash flags, a script path ending in skills/chronicle/scripts/chronicle.py, then
# `context` and plain options. A command that merely mentions chronicle, runs something else
# (echo, rm, cat) or chains more shell (; & | < > ` $ or a newline) is the user's and is never taken over.
_HOOK_WORD = r"[^\s\"';&|<>`$()]"
_HOOK_SCRIPT = r"[/\\]skills[/\\]chronicle[/\\]scripts[/\\]chronicle\.py"
_HOOK_INTERP = r"(?:\"(?:[^\"`$\n]*[/\\])?{n}\"|(?:{w}*[/\\])?{n})".format(
    n=r"(?:py|python(?:\d+(?:\.\d+)?)?)(?:\.exe)?", w=_HOOK_WORD)
_CHRONICLE_HOOK_RE = re.compile(
    r"[ \t]*" + _HOOK_INTERP + r"(?:[ \t]+-{w}+)*[ \t]+"
    r"(?:\"[^\"`$\n]*{s}\"|'[^'\n]*{s}'|{w}*{s})"
    r"[ \t]+context(?:[ \t]+{w}+)*[ \t]*".format(w=_HOOK_WORD, s=_HOOK_SCRIPT))


def is_chronicle_handler(handler):
    return isinstance(handler, dict) and bool(_CHRONICLE_HOOK_RE.fullmatch(str(handler.get("command", ""))))


def hook_handler(platform, command):
    handler = {"type": "command", "command": command, "timeout": HOOK_TIMEOUT}
    if platform == "codex":
        handler["additionalContextLimit"] = CODEX_CONTEXT_LIMIT
    return handler


def merge_session_hook(data, handler, matcher):
    """Return a copy of a settings/hooks JSON object with exactly one chronicle SessionStart hook.

    An existing chronicle handler is updated where it is: Codex keys hook trust by group and
    handler position, so moving groups would make it skip the user's other hooks until re-trusted.
    """
    import json

    if not isinstance(data, dict):
        raise ChronicleError("top level is not a JSON object")
    data = json.loads(json.dumps(data))
    hooks = data.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        raise ChronicleError('"hooks" is not a JSON object')
    groups = hooks.get("SessionStart", [])
    if not isinstance(groups, list):
        raise ChronicleError('"hooks.SessionStart" is not a list')
    kept, placed = [], False
    for group in groups:
        if isinstance(group, dict) and isinstance(group.get("hooks"), list) \
                and any(is_chronicle_handler(h) for h in group["hooks"]):
            own_group = all(is_chronicle_handler(h) for h in group["hooks"])
            handlers = []
            for h in group["hooks"]:
                if not is_chronicle_handler(h):
                    handlers.append(h)
                elif not placed:  # update the first one in place (keeping extra keys); drop duplicates
                    updated = dict(h, **handler)
                    for key in HOOK_USER_KEYS:  # the user's own timing and spill settings win
                        if key in h:
                            updated[key] = h[key]
                    handlers.append(updated)
                    placed = True
            if not handlers:
                continue
            group = dict(group, hooks=handlers)
            if own_group:
                group["matcher"] = matcher
        kept.append(group)
    if not placed:
        kept.append({"matcher": matcher, "hooks": [handler]})
    hooks["SessionStart"] = kept
    return data


def apply_hook_file(path, handler, matcher):
    import json
    import shutil

    real = os.path.realpath(path)  # write through a symlink (e.g. into a dotfiles repo), never replace it
    existed = os.path.lexists(path)
    data = {}
    if existed:
        if not os.path.isfile(real):
            raise ChronicleError("%s is not a regular file; left unchanged" % path)
        try:
            with open(real, encoding="utf-8-sig") as f:  # -sig: some Windows editors write a BOM
                raw = f.read()
            data = json.loads(raw) if raw.strip() else {}
        except (OSError, ValueError) as e:
            raise ChronicleError("%s is not readable JSON (%s); left unchanged" % (path, e))
    merged = merge_session_hook(data, handler, matcher)
    if existed and merged == data:
        return "SessionStart hook already present: %s" % path
    note = ""
    backup = path + ".bak-chronicle"
    try:
        if existed:
            if os.path.lexists(backup):  # keep the first backup: it is the pre-chronicle original
                note = " (original kept in %s)" % os.path.basename(backup)
            else:
                shutil.copy2(real, backup)
                note = " (backup: %s)" % os.path.basename(backup)
        else:
            os.makedirs(os.path.dirname(real), exist_ok=True)
        tmp = real + ".tmp-chronicle"
        write_text(tmp, json.dumps(merged, indent=2, ensure_ascii=False) + "\n")
        if existed:
            shutil.copymode(real, tmp)
        os.replace(tmp, real)
    except OSError as e:
        raise ChronicleError("cannot update %s (%s)" % (path, e))
    return "wrote SessionStart hook: %s%s" % (path, note)


def _remove_path(path):
    """Delete a directory tree; a symlink or file is unlinked (a link's target is never touched)."""
    import shutil

    if os.path.isdir(path) and not os.path.islink(path):
        shutil.rmtree(path)
    else:
        os.unlink(path)


def copy_skill(src, dest):
    """Replace dest with a copy of src without ever leaving dest missing or half-written.

    The copy is staged next to dest, the current installation (directory or symlink) is moved
    aside, the staged copy is renamed into place, and only then is the old one deleted. Any
    failure before that restores the old installation.
    """
    import shutil

    if os.path.exists(dest) and os.path.realpath(src) == os.path.realpath(dest):
        return "skill already in place: %s" % dest
    tmp, old = dest + ".tmp-chronicle", dest + ".old-chronicle"
    if os.path.lexists(old):
        raise ChronicleError("%s exists (left by an interrupted install): move it back to %s or delete it, "
                             "then rerun; nothing changed" % (old, dest))
    try:
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        if os.path.lexists(tmp):
            _remove_path(tmp)  # an earlier run's staging copy: chronicle's own files only
        shutil.copytree(src, tmp, ignore=shutil.ignore_patterns("__pycache__", "*.pyc", ".DS_Store"))
    except OSError as e:  # shutil.Error is an OSError
        if os.path.lexists(tmp):
            shutil.rmtree(tmp, ignore_errors=True)
        raise ChronicleError("cannot stage the skill copy %s (%s); %s left unchanged" % (tmp, e, dest))
    moved = False
    try:
        if os.path.lexists(dest):
            os.replace(dest, old)
            moved = True
        os.replace(tmp, dest)
    except OSError as e:
        if moved:
            try:
                os.replace(old, dest)
            except OSError as e2:
                raise ChronicleError("cannot install %s (%s) nor restore it (%s): the previous installation "
                                     "is in %s; move it back" % (dest, e, e2, old))
        shutil.rmtree(tmp, ignore_errors=True)
        raise ChronicleError("cannot install %s (%s); previous installation left in place" % (dest, e))
    if moved:
        try:
            _remove_path(old)
        except OSError as e:
            return "installed skill: %s (could not delete the previous copy %s: %s; delete it by hand)" % (
                dest, old, e)
    return "installed skill: %s" % dest


def install(home, platforms, hooks, python):
    """Copy the skill and optionally merge SessionStart hooks; returns (lines, ok)."""
    lines, ok = [], True
    if hooks and WSL_DRIVE_RE.match(home):
        lines.append(
            "warning: %s is a Windows drive mounted in WSL: the hook command written there is a Linux "
            "command (%s on a /mnt path) that Windows Claude Code and Codex cannot run. Install from "
            "Windows instead: py -3 <checkout>\\skills\\chronicle\\scripts\\chronicle.py install --hooks"
            % (home, python))
    src = skill_source_dir()
    for platform in platforms:
        dest = os.path.join(home, "." + platform, "skills", "chronicle")
        try:
            lines.append(copy_skill(src, dest))
        except ChronicleError as e:
            lines.append("error: %s" % e)
            ok = False
            continue  # no hook pointing at a skill that is not installed
        if not hooks:
            continue
        script = os.path.join(dest, "scripts", "chronicle.py")
        cfg = os.path.join(home, ".claude", "settings.json") if platform == "claude" \
            else os.path.join(home, ".codex", "hooks.json")
        try:
            handler = hook_handler(platform, hook_command(python, script))
            lines.append(apply_hook_file(cfg, handler, HOOK_MATCHERS[platform]))
        except ChronicleError as e:
            lines.append("error: %s" % e)
            ok = False
    if hooks and "codex" in platforms:
        lines.append("note: Codex runs new or changed hooks only after you review and trust them: run /hooks in Codex.")
    if not hooks:
        lines.append("hint: rerun with --hooks to inject the memory index at session start.")
    return lines, ok


# --------------------------------------------------------------------------- commands


def cmd_context(args):
    try:
        text = context_text(find_root(args.cwd) or os.path.abspath(args.cwd), args.max_bytes)
    except Exception:
        text = ""
    if text:
        sys.stdout.write(text)
    return 0


def cmd_index(args):
    root = repo_root(args.cwd)
    if not os.path.isdir(rpath(root, MEMORY_REL)):
        raise ChronicleError("%s does not exist (run chronicle init)" % MEMORY_REL)
    memories, _ = scan_store(root)
    for m in memories:
        if not m.indexable:
            print("skipped %s: %s (see chronicle lint)" % (m.rel, m.error or "invalid type"), file=sys.stderr)
    expected = render_index(memories)
    n = count_entries(expected)
    if args.check:
        if read_index(root) != expected:
            print("%s is out of date (run chronicle index)" % INDEX_REL)
            return 1
        print("%s is up to date (%d entries)" % (INDEX_REL, n))
        return 0
    changed = write_index(root, memories)
    print("%s %s (%d entries)" % ("wrote" if changed else "unchanged:", INDEX_REL, n))
    return 0


def cmd_lint(args):
    root = repo_root(args.cwd)
    findings, n = lint_store(root)
    for level, path, msg in findings:
        print("%s %s: %s" % (level, path, msg))
    errors = sum(1 for f in findings if f[0] == "ERROR")
    warnings = len(findings) - errors
    print("chronicle lint: %d memories, %d errors, %d warnings" % (n, errors, warnings), file=sys.stderr)
    return 1 if errors or (args.strict and warnings) else 0


def cmd_new(args):
    root = repo_root(args.cwd)
    slug = args.slug
    description = " ".join(args.description.split())
    if not NAME_RE.match(slug):
        raise ChronicleError("invalid slug `%s`: use 3-64 chars of a-z, 0-9 and -, starting with a letter or digit" % slug)
    if args.type == "status" and not slug.startswith("status-"):
        raise ChronicleError("status entries must be named status-<branch or topic>, e.g. status-%s" % slug)
    if not description:
        raise ChronicleError("--description must not be empty")
    if len(description) > DESCRIPTION_MAX:
        print("warning: description is %d chars (budget %d)" % (len(description), DESCRIPTION_MAX), file=sys.stderr)
    path = rpath(root, MEMORY_REL + "/" + slug + ".md")
    if os.path.exists(path):
        raise ChronicleError("%s/%s.md already exists: update it instead" % (MEMORY_REL, slug))
    for action in ensure_store(root):
        print(action, file=sys.stderr)
    content = "---\nname: %s\ndescription: %s\ntype: %s\nupdated: %s\n---\n%s" % (
        slug, yaml_scalar(description), args.type, today().isoformat(), BODY_TEMPLATE)
    try:
        with open(path, "x", encoding="utf-8", newline="\n") as f:
            f.write(content)
    except FileExistsError:
        raise ChronicleError("%s/%s.md already exists: update it instead" % (MEMORY_REL, slug))
    write_index(root)
    print(path)
    return 0


def cmd_init(args):
    root = repo_root(args.cwd)
    actions = ensure_store(root)
    for action in actions:
        print(action)
    if not actions:
        print("already initialized: %s" % rpath(root, MEMORY_REL))
    return 0


def cmd_migrate_plan(args):
    root = repo_root(args.cwd)
    print("\n".join(migrate_plan(root)))
    return 0


def cmd_install(args):
    home = os.path.abspath(os.path.expanduser(args.home or "~"))
    platforms = [p for p, flag in (("claude", args.claude), ("codex", args.codex)) if flag]
    if not platforms:
        platforms = [p for p in ("claude", "codex") if os.path.isdir(os.path.join(home, "." + p))]
    if not platforms:
        raise ChronicleError("neither %s nor %s exists; pass --claude and/or --codex"
                             % (os.path.join(home, ".claude"), os.path.join(home, ".codex")))
    lines, ok = install(home, platforms, args.hooks, args.python or default_python())
    print("\n".join(lines))
    return 0 if ok else 1


def build_parser():
    import argparse

    ap = argparse.ArgumentParser(prog="chronicle", description="Shared project memory in docs/memory (see SKILL.md).")
    sub = ap.add_subparsers(dest="command", metavar="command")
    sub.required = True

    def add(name, text, func):
        sp = sub.add_parser(name, help=text, description=text)
        sp.add_argument("--cwd", default=".", help="a directory inside the target repo (default: .)")
        sp.set_defaults(func=func)
        return sp

    sp = add("context", "print the memory index for a SessionStart hook (never fails)", cmd_context)
    sp.add_argument("--max-bytes", type=int, default=CONTEXT_MAX_BYTES,
                    help="output budget in bytes (default %d, minimum %d)" % (CONTEXT_MAX_BYTES, CONTEXT_MIN_BYTES))
    sp = add("index", "regenerate docs/memory/MEMORY.md", cmd_index)
    sp.add_argument("--check", action="store_true", help="write nothing; exit 1 if out of date")
    sp = add("lint", "validate the memory store", cmd_lint)
    sp.add_argument("--strict", action="store_true", help="fail on warnings too")
    sp = add("new", "scaffold a memory file and reindex", cmd_new)
    sp.add_argument("type", choices=TYPES)
    sp.add_argument("slug")
    sp.add_argument("--description", "-d", required=True)
    add("init", "create docs/memory, MEMORY.md and the .gitattributes union line", cmd_init)
    add("migrate-plan", "read-only inventory and checklist for legacy memory", cmd_migrate_plan)
    sp = add("install", "copy this skill to ~/.claude and/or ~/.codex; optional SessionStart hooks", cmd_install)
    sp.add_argument("--claude", action="store_true", help="install for Claude Code")
    sp.add_argument("--codex", action="store_true", help="install for Codex")
    sp.add_argument("--home", help="home directory (default: ~)")
    sp.add_argument("--hooks", action="store_true", help="merge a SessionStart hook running `context`")
    sp.add_argument("--python", help='interpreter command for the hook (default: "python3"; "py -3" on Windows)')
    return ap


def _utf8_stdio():
    """UTF-8 and LF on every platform: hooks read bytes, and the context budget counts them."""
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace", newline="\n")
        except Exception:
            pass


def main(argv=None):
    _utf8_stdio()
    args = build_parser().parse_args(argv)
    try:
        return args.func(args)
    except (ChronicleError, OSError) as e:  # OSError: unwritable or vanished paths, no traceback
        print("chronicle: %s" % e, file=sys.stderr)
        return 2


if __name__ == "__main__":
    argv = sys.argv[1:]
    if argv[:1] == ["context"] and not ({"-h", "--help"} & set(argv)):
        run_context_hook(argv[1:])
    sys.exit(main(argv))
